apiVersion: v1
kind: ConfigMap
metadata:
  name: appointment-config
data:
  PORT: "3001"
  CLIENT_URL: "http://localhost:30082"
apiVersion: v1
kind: ConfigMap
metadata:
  name: appointment-config
data:
  PORT: "3001"
  # Gateway endpoints (the API gateway service should be present in the cluster)
  PATIENT_SERVICE_URL: "http://api-gateway:5400/api/patients"
  DOCTOR_SERVICE_URL: "http://api-gateway:5400/api/auth/doctors"
  NOTIFICATION_SERVICE_URL: "http://api-gateway:5400/api/notifications"
