apiVersion: v1
kind: Secret
metadata:
  name: appointment-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongodb:27017/appointment-service"
apiVersion: v1
kind: Secret
metadata:
  name: appointment-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongodb:27017/appointment-management"
  INTERNAL_API_KEY: "gateway-secret-key-change-in-production"
