apiVersion: v1
kind: Secret
metadata:
  name: doctor-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://Doctor:doctor123@farm.asobfd5.mongodb.net/doctor_serviceDB?retryWrites=true&w=majority"
  JWT_SECRET: health_center_backend_secret_key_2026_secure