apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://Doctor:doctor123@farm.asobfd5.mongodb.net/notification-service?retryWrites=true&w=majority"
apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://Doctor:doctor123@farm.asobfd5.mongodb.net/notification-service?retryWrites=true&w=majority"
  INTERNAL_API_KEY: "gateway-secret-key-change-in-production"
