apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
        - name: redpanda
          image: vectorized/redpanda:latest
          args:
            - redpanda
            - start
            - --overprovisioned
            - --smp
            - "1"
            - --reserve-memory
            - "0M"
            - --node-id
            - "0"
            - --check=false
            - --kafka-addr
            - "PLAINTEXT://0.0.0.0:29092"
            - --advertise-kafka-addr
            - "PLAINTEXT://kafka:29092"
          ports:
            - containerPort: 29092
