apiVersion: v1
kind: Secret
metadata:
  name: telemedicine-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://Doctor:doctor123@farm.asobfd5.mongodb.net/telemedicine_serviceDB?retryWrites=true&w=majority"